name: "Issue template"
description: Create a new ticket for a new feature or a change in our application.
title: "WI-<title of the change or the new feature you woould like to have>"
labels:
  - "WI"
body:
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: Brief description (one-line) of the change
      placeholder: "E.g., The app doesnt support multiple login"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Detailed description"
      description: Provide instructions to understand what you want to have in the app.
      placeholder: |
      "I'd like to be able to login using google and/or github. I don't want to be forced to create
      an account. My idea is having some options such as 'continue with github' or 'continue with 
      google' in the sign in/up view."
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      description: Select the priority level of this issue.
      options:
        - High
        - Medium
        - Low

  - type: textarea
    id: other_details
    attributes:
      label: "Additional details"
      description: Include any other relevant details about your proposition.
      placeholder: "E.g., Plugins, etc."
