name: Deploy to Main

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install selenium

      # Descomenta y ajusta este paso si tienes pruebas Selenium
      # - name: Run Selenium tests
      #   run: |
      #     for test_file in $(find app/modules -type f -path "*/tests/test_*.py"); do
      #       python "$test_file"
      #     done

      - name: Debug GitHub Token
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        run: |
          curl -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/EGC-Serranito/serranito-hub

  create_and_merge_pr:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Asegura que se obtenga todo el historial de Git

      - name: Crear y Mergear Pull Request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ADMIN_TOKEN }}
          script: |
            const sourceBranch = 'develop';
            const targetBranch = 'main';
            const prTitle = 'Merge cambios de develop a main';
            const prBody = 'Esta PR integra todos los cambios de la rama develop en main para mantener la rama principal actualizada.';
            
            // Función para esperar hasta que 'mergeable' no sea null
            async function waitForMergeable(owner, repo, pull_number, retries = 5, delay = 3000) {
              for (let i = 0; i < retries; i++) {
                const { data: pr } = await github.rest.pulls.get({
                  owner,
                  repo,
                  pull_number,
                });
                if (pr.mergeable !== null) {
                  return pr.mergeable;
                }
                console.log(`Esperando a que GitHub determine si la PR es mergeable... Intento ${i + 1}/${retries}`);
                await new Promise(res => setTimeout(res, delay));
              }
              return null;
            }
            
            // Verificar si ya existe una PR abierta desde develop a main
            const { data: existingPRs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.repo.owner}:${sourceBranch}`,
              base: targetBranch,
              state: 'open',
            });
            
            if (existingPRs.length > 0) {
              console.log(`Ya existe una PR abierta: #${existingPRs[0].number}. Verificando si es mergeable.`);
              
              const pr = existingPRs[0];
              let mergeable = pr.mergeable;
              
              if (mergeable === null) {
                // Esperar hasta que GitHub determine si es mergeable
                mergeable = await waitForMergeable(context.repo.owner, context.repo.repo, pr.number);
              }
              
              if (mergeable) {
                console.log(`La PR #${pr.number} es mergeable. Procediendo a mergearla.`);
                const mergeResponse = await github.rest.pulls.merge({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: pr.number,
                  commit_title: `chore: merge changes from ${sourceBranch} into ${targetBranch}`,
                  commit_message: `Merging updates from ${sourceBranch} into ${targetBranch} to keep production up-to-date.`,
                  merge_method: 'squash',
                });
                
                if (mergeResponse.status === 200) {
                  console.log(`PR #${pr.number} mergeada exitosamente.`);
                } else {
                  console.log(`No se pudo mergear la PR #${pr.number}. Estado: ${mergeResponse.status}`);
                }
              } else {
                console.log(`La PR #${pr.number} no es mergeable. Revisar manualmente.`);
              }
              return;
            }
            
            // Comparar las ramas para verificar si hay commits que no están en main
            const comparison = await github.rest.repos.compareCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: targetBranch,
              head: sourceBranch,
            });
            
            if (comparison.data.behind_by === 0 && comparison.data.ahead_by === 0) {
              console.log('No hay cambios nuevos para mergear.');
              return;
            }
            
            if (comparison.data.ahead_by === 0) {
              console.log('La rama develop no tiene nuevos commits respecto a main.');
              return;
            }
            
            // Crear una nueva PR
            const { data: pr } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: prTitle,
              head: sourceBranch,
              base: targetBranch,
              body: prBody,
            });
            
            console.log(`PR creada: #${pr.number}. Verificando si es mergeable.`);
            
            let newMergeable = pr.mergeable;
            
            if (newMergeable === null) {
              newMergeable = await waitForMergeable(context.repo.owner, context.repo.repo, pr.number);
            }
            
            if (newMergeable) {
              console.log(`La PR #${pr.number} es mergeable. Procediendo a mergearla.`);
              const mergeNewPR = await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                commit_title: `chore: merge changes from ${sourceBranch} into ${targetBranch}`,
                commit_message: `Merging updates from ${sourceBranch} into ${targetBranch} to keep production up-to-date.`,
                merge_method: 'squash',
              });
              
              if (mergeNewPR.status === 200) {
                console.log(`PR #${pr.number} mergeada exitosamente.`);
              } else {
                console.log(`No se pudo mergear la PR #${pr.number}. Estado: ${mergeNewPR.status}`);
              }
            } else {
              console.log(`La PR #${pr.number} no es mergeable. Revisar manualmente.`);
            }
            
          debug: false
          user-agent: actions/github-script
          result-encoding: json
          retries: 0
          retry-exempt-status-codes: 400,401,403,404,422

      - name: Verificar Merge
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ADMIN_TOKEN }}
          script: |
            const targetBranch = 'main';
            const commits = await github.rest.repos.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: targetBranch,
              per_page: 5,
            });
            
            console.log(`Últimos commits en ${targetBranch}:`);
            commits.data.forEach(commit => {
              console.log(`- ${commit.commit.message} (${commit.sha.substring(0, 7)})`);
            });

  create_release:
    needs: create_and_merge_pr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Generar changelog
        id: generate_changelog
        run: |
          PREV_TAG=$(git describe --tags `git rev-list --tags --skip=1 --max-count=1`)
          CURR_TAG=${GITHUB_REF#refs/tags/}
          
          echo "Generating changelog from commits between $PREV_TAG and $CURR_TAG"
          CHANGELOG=$(git log $PREV_TAG..$CURR_TAG --pretty=format:"- %s")
          
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Crear Release en GitHub
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ${{ steps.generate_changelog.outputs.changelog }}
            Full Changelog: https://github.com/EGC-Serranito/serranito-hub/commits/${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
