name: Populate render dev database 

on:
  push:
      branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e ./

      - name: Create .env file from GitHub Secrets
        run: |
          echo "FILESS_DB_USER=${{ secrets.FILESS_PROD_DB_USER }}" >> .env
          echo "FILESS_DB_PASSWORD=${{ secrets.FILESS_PROD_DB_PASSWORD }}" >> .env
          echo "FILESS_DB_HOST=${{ secrets.FILESS_PROD_DB_HOST }}" >> .env
          echo "FILESS_DB_PORT=${{ secrets.FILESS_PROD_DB_PORT }}" >> .env
          echo "FILESS_DB_NAME=${{ secrets.FILESS_PROD_DB_NAME }}" >> .env


      - name: Populate database
        run: |
            python3 scripts/special/updateLastLine.py
            rosemary populate:db_dev